// Top level: NetFirm-4E40-C (XC7K325T-FFG900-2) configuration-memory fault-injection platform.
//   sysclk 100 MHz (AB27/AC27 LVDS) -> BUFG -> SEM controller, FI controller, DUT (single clock).
//   Host access only through JTAG USER1..4 (see jtag_regs.v); LEDs show liveness.
//   Board-specific: U27 and the BPI flash control pins are inputs with weak pull-ups.
`timescale 1ns / 1ps
module fi_top #(
    // set per build by hw/tcl/build.tcl (synth_design -generic) from hw/gen/<model>/meta.json
    parameter IN_W    = 160,     // DUT input width
    parameter CW      = 3,       // class-index width
    parameter NVEC    = 4096,    // test vectors
    parameter LATENCY = 4,       // DUT pipeline latency
    parameter VEC_FILE = "vectors.mem",
    parameter FAR_FILE = "farlist.mem",
    parameter [15:0] BUILD_ID = 16'h0001,
    parameter [15:0] DUT_ID   = 16'h0000
) (
    input  wire       sysclk_p,
    input  wire       sysclk_n,
    input  wire       keep_u27,        // weak pull-up input
    input  wire [3:0] keep_flash,      // FCS_B, FOE_B, FWE_B, ADV_B: weak pull-up inputs
    output wire [7:0] led
);
    localparam WIN_N = 128;
    localparam WINW  = 64 + 64 * WIN_N;
    localparam MONW  = 32 + 256 * 8;

    wire clk_ibuf, clk;
    IBUFDS #(.DIFF_TERM("FALSE"), .IOSTANDARD("LVDS_25")) u_ibufds (.I(sysclk_p), .IB(sysclk_n), .O(clk_ibuf));
    BUFG u_bufg (.I(clk_ibuf), .O(clk));

    // ---------------- SEM controller ----------------
    // Soft Error Mitigation IP v4.1 (hw/tcl/gen_sem_ip.tcl: 100 MHz, error injection and correction
    // enabled, repair mode). It owns the ICAP; the FI controller drives its injection interface.
    wire st_hb, st_init, st_obs, st_cor, st_cls, st_inj, st_ess, st_unc;
    wire [7:0] mon_txdata;
    wire mon_txwrite, mon_txfull, mon_rxread;
    wire inject_strobe;
    wire [39:0] inject_address;
    wire [31:0] icap_o, icap_i;
    wire icap_csib, icap_rdwrb, icap_req;
    wire fecc_crcerr, fecc_eccerr, fecc_eccerrsingle, fecc_syndromevalid;
    wire [12:0] fecc_syndrome;
    wire [25:0] fecc_far;
    wire [4:0] fecc_synbit;
    wire [6:0] fecc_synword;
    sem_0 u_sem (
        .status_heartbeat(st_hb), .status_initialization(st_init), .status_observation(st_obs),
        .status_correction(st_cor), .status_classification(st_cls), .status_injection(st_inj),
        .status_essential(st_ess), .status_uncorrectable(st_unc),
        .monitor_txdata(mon_txdata), .monitor_txwrite(mon_txwrite), .monitor_txfull(mon_txfull),
        .monitor_rxdata(8'h00), .monitor_rxread(mon_rxread), .monitor_rxempty(1'b1),
        .inject_strobe(inject_strobe), .inject_address(inject_address),
        .icap_o(icap_o), .icap_csib(icap_csib), .icap_rdwrb(icap_rdwrb), .icap_i(icap_i),
        .icap_clk(clk), .icap_request(icap_req), .icap_grant(1'b1),   // no other ICAP user

        .fecc_crcerr(fecc_crcerr), .fecc_eccerr(fecc_eccerr), .fecc_eccerrsingle(fecc_eccerrsingle),
        .fecc_syndromevalid(fecc_syndromevalid), .fecc_syndrome(fecc_syndrome), .fecc_far(fecc_far),
        .fecc_synbit(fecc_synbit), .fecc_synword(fecc_synword));
    sem_cfg u_cfg (
        .icap_clk(clk), .icap_o(icap_o), .icap_csib(icap_csib), .icap_rdwrb(icap_rdwrb), .icap_i(icap_i),
        .fecc_crcerr(fecc_crcerr), .fecc_eccerr(fecc_eccerr), .fecc_eccerrsingle(fecc_eccerrsingle),
        .fecc_syndromevalid(fecc_syndromevalid), .fecc_syndrome(fecc_syndrome), .fecc_far(fecc_far),
        .fecc_synbit(fecc_synbit), .fecc_synword(fecc_synword));

    // ---------------- SEM monitor text capture (256-byte ring) ----------------
    wire mon_freeze;
    wire [MONW-1:0] mon_vec;
    sem_mon_cap u_mon (.clk(clk), .txdata(mon_txdata), .txwrite(mon_txwrite), .freeze(mon_freeze),
                       .txfull(mon_txfull), .mon(mon_vec));

    // ---------------- JTAG registers and controller ----------------
    wire [255:0] cmd;
    wire cmd_valid;
    wire [511:0] status;
    wire [WINW-1:0] window;
    jtag_regs #(.WINW(WINW), .MONW(MONW)) u_jtag (
        .clk(clk), .status(status), .cmd(cmd), .cmd_valid(cmd_valid),
        .window(window), .mon(mon_vec), .mon_freeze(mon_freeze));

    wire [IN_W-1:0] dut_x;
    wire [CW-1:0] dut_y;
    fi_ctrl #(.IN_W(IN_W), .CW(CW), .NVEC(NVEC), .LATENCY(LATENCY), .WIN_N(WIN_N), .VEC_FILE(VEC_FILE), .FAR_FILE(FAR_FILE),
              .BUILD_ID(BUILD_ID), .DUT_ID(DUT_ID)) u_ctrl (
        .clk(clk), .cmd(cmd), .cmd_valid(cmd_valid), .status(status), .window(window),
        .inject_strobe(inject_strobe), .inject_address(inject_address),
        .sem_st({st_unc, st_ess, st_inj, st_cls, st_cor, st_obs, st_init, st_hb}),
        .dut_x(dut_x), .dut_y(dut_y));

    // The network under test (generated by train/gen_dut.py). Its hierarchy is kept so that the
    // build script can confine it to its own pblock and the analysis can identify its cells.
    (* KEEP_HIERARCHY = "yes" *) dut u_dut (.clk(clk), .x(dut_x), .y(dut_y));

    // ---------------- LEDs ----------------
    reg [26:0] beat = 0;
    always @(posedge clk) beat <= beat + 1'b1;
    reg [7:0] led_r = 0;
    always @(posedge clk) led_r <= {&{keep_u27, keep_flash}, 1'b0, status[31], status[29], st_inj, st_obs, st_hb, beat[26]};
    assign led = led_r;   // [0] 0.75 Hz beat [1] SEM heartbeat [2] observation [3] injection [4] running [5] error [7] pull-ups read 1
endmodule

// ICAPE2 + FRAME_ECCE2 wrapper (from the SEM v4.1 example design). FRAME_ECCE2 checks the ECC of
// every frame the SEM reads back; FARSRC "EFAR" reports the address of the frame being read.
module sem_cfg (
    input  wire        icap_clk,
    output wire [31:0] icap_o,
    input  wire        icap_csib,
    input  wire        icap_rdwrb,
    input  wire [31:0] icap_i,
    output wire        fecc_crcerr,
    output wire        fecc_eccerr,
    output wire        fecc_eccerrsingle,
    output wire        fecc_syndromevalid,
    output wire [12:0] fecc_syndrome,
    output wire [25:0] fecc_far,
    output wire  [4:0] fecc_synbit,
    output wire  [6:0] fecc_synword
);
    FRAME_ECCE2 #(.FRAME_RBT_IN_FILENAME("NONE"), .FARSRC("EFAR")) example_frame_ecc (
        .CRCERROR(fecc_crcerr), .ECCERROR(fecc_eccerr), .ECCERRORSINGLE(fecc_eccerrsingle),
        .FAR(fecc_far), .SYNBIT(fecc_synbit), .SYNDROME(fecc_syndrome),
        .SYNDROMEVALID(fecc_syndromevalid), .SYNWORD(fecc_synword));
    ICAPE2 #(.DEVICE_ID(32'hFFFFFFFF), .SIM_CFG_FILE_NAME("NONE"), .ICAP_WIDTH("X32")) example_icap (
        .O(icap_o), .CLK(icap_clk), .CSIB(icap_csib), .I(icap_i), .RDWRB(icap_rdwrb));
endmodule

// SEM monitor TX capture: 256-byte ring buffer + write pointer, readable over JTAG USER4.
// While the host reads (freeze), txfull stalls the SEM controller so no byte is lost.
module sem_mon_cap (
    input  wire         clk,
    input  wire [7:0]   txdata,
    input  wire         txwrite,
    input  wire         freeze,
    output wire         txfull,
    output wire [2079:0] mon
);
    reg [7:0]  ring [0:255];
    reg [15:0] wp = 0;
    integer i;
    initial for (i = 0; i < 256; i = i + 1) ring[i] = 8'h00;
    assign txfull = freeze;
    always @(posedge clk) if (txwrite && !freeze) begin ring[wp[7:0]] <= txdata; wp <= wp + 1'b1; end
    genvar g;
    generate for (g = 0; g < 256; g = g + 1) begin : g_mon
        assign mon[32 + g*8 +: 8] = ring[g];
    end endgenerate
    assign mon[31:0] = {wp, 16'h4D4E};   // 'MN'
endmodule
